//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Common;

namespace ExtendedSearch
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExtendedSearchEntities : DbContext
    {
        public ExtendedSearchEntities()
            : base("name=ExtendedSearchEntities")
        {
        }

		// This constructor is used by Effort in the tests.
		public ExtendedSearchEntities(DbConnection connection)
        : base(connection, true)
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Engine> Engines { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
    }
}
